# PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/LAB_7_MusicViewer
spring.datasource.username=postgres
spring.datasource.password=1

# JPA
hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=validate